parameters:
  - name: npmVersion
    type: string
    default: '12.22.9'

  - name: artifactName
    type: string
    default: 'drop'
  
  - name: AZ_DEVOPS_POOL
    default: ''

  - name: artifactToPublish
    default: ''

stages:
- stage: "Build"
  displayName: 'Build App'
  jobs:

  - job: BuildNPM
    pool:
      vmImage: ${{ parameters.AZ_DEVOPS_POOL }}
    steps:

      - checkout: self
        fetchDepth: 1

      - task: UseNode@1
        inputs:
          version: ${{ parameters.npmVersion }}
        displayName: 'Install Node.js'

      - script: |
          npm install --force
        displayName: 'npm install'

      - script: |
          npm run build
        displayName: 'npm build'

      - task: CopyFiles@2
        inputs:
          sourceFolder: '$(Build.SourcesDirectory)/${{ parameters.artifactToPublish }}'
          contents: "**"
          targetFolder: '$(Build.ArtifactStagingDirectory)'
        displayName: 'Copy project files'

      - task: PublishPipelineArtifact@1
        inputs:
          artifactName: ${{ parameters.artifactName }}
          targetPath: '$(Build.ArtifactStagingDirectory)'
          publishLocation: 'pipeline'
        displayName: 'Publish artifact'
