# File: azure-pipelines.yaml

jobs:

- template: examples/jobs/build.yaml  # Template reference
  parameters:
    name: macOS
    pool:
      vmImage: 'macOS-latest'


- template: examples/jobs/build.yaml  # Template reference
  parameters:
    name: Linux
    pool:
      vmImage: 'ubuntu-latest'


- template: examples/jobs/build.yaml  # Template reference
  parameters:
    name: Windows 
    pool:
      vmImage: 'windows-latest'
    sign: true  # Extra step on Windows only